export const myWorks = [
  {
    id: 0,
    img: "./imgs/vue_chat_proyect.webp",
    title: "Vue Chat Project",
    description: "This SPA is made with Vue, Pinia and Bootstrap 5, and uses Firebase for Authentication, Data Storage and Chat functionality.",
    github: "https://github.com/derpmagician/fbvue3-exp",
    demo: "https://derpmagician.github.io/fbvue3-exp/",
  },
  {
    id: 1,
    img: "./imgs/user_administrator.webp",
    title: "User Administrator",
    description: "This SPA fetches an API and uses React, Routes and Redux to manipulate data and change users' roles and location. It also has Auth0 authentication.",
    github: "https://github.com/derpmagician/user-administration-react-redux",
    demo: "https://derpmagician.github.io/user-administration-react-redux/",
  },
  {
    id: 2,
    img: "./imgs/shorten.png",
    title: "Shorten",
    description: "Link shortener made with Node, React and MongoDB. It checks if the given URL already exists in the database; if not, it generates a short ID that can be used to access the original URL.",
    github: "https://github.com/derpmagician/shorten",
    demo: null,
  },
  {
    id: 3,
    img: "./imgs/image_filters.webp",
    title: "Image Filters",
    description: "Image editor in React with a save feature that manipulates the CSS.",
    github: "https://github.com/derpmagician/react_img_filters",
    demo: "https://derpmagician.github.io/react_img_filters/",
  },
  {
    id: 4,
    img: "./imgs/tower_defense_js.webp",
    title: "Tower Defense Js",
    description: "Vanilla JavaScript game that uses the HTML Canvas element and JS classes to create the game objects.",
    github: "https://github.com/derpmagician/towerdefencejs",
    demo: "https://derpmagician.github.io/towerdefencejs/",
  },
  // {
  //   id: 5,
  //   img: "https://i.imgur.com/F5OH2m1.png",
  //   title: "Space X Missions",
  //   description: "Fetching a Graphql API with React, UseEffect",
  //   github: "https://github.com/derpmagician/consumographqlspacex",
  //   demo: "https://derpmagician.github.io/consumographqlspacex/",
  // },
  {
    id: 6,
    img: "./imgs/screen_saver_emulator.webp",
    title: "Screen Saver Emulator",
    description: "Manipulates CSS properties to draw the '3D' objects and uses vanilla JS to activate the timer that makes the screen appear.",
    github: "https://github.com/derpmagician/ScreenSaver-Sim",
    demo: "https://derpmagician.github.io/ScreenSaver-Sim/",
  },
]
